// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FrontendLogService is the Go binding service the frontend calls: it receives frontend
 * logs/errors and writes them to frontend.log.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

/**
 * FrontendLog is called by the frontend: level is debug/info/warn/error, msg is the log
 * text.
 */
export function FrontendLog(level: string, msg: string): $CancellablePromise<void> {
    return $Call.ByID(1142342357, level, msg);
}

/**
 * SetLevel syncs the frontend log level (called by applyLogConfig).
 */
export function SetLevel(level: slog$0.Level): $CancellablePromise<void> {
    return $Call.ByID(413077503, level);
}
