// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the app's core facade (thin Wrapper):
 *   - The only implementer of the wails lifecycle trio (ServiceStartup / ServiceShutdown /
 *     ServiceName), and the single entry point for the global startup orchestration (engine
 *     loading, hotkey registration, language/accessibility initialization).
 *   - Holds references to the domain services and Wrappers — the hub for dependency
 *     injection.
 *   - Only exposes core RPCs (version, accessibility, startup orchestration);
 *     translation/history/config/window RPCs belong to the individual Wrappers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * CheckAccessibility checks whether macOS accessibility is authorized (cross-platform:
 * non-darwin returns true directly).
 */
export function CheckAccessibility(): $CancellablePromise<boolean> {
    return $Call.ByID(1415430577);
}

/**
 * CheckInputMonitoring checks whether macOS Input Monitoring is authorized (translate on double
 * Cmd+C needs it; cross-platform: non-darwin returns true directly). The Settings page polls it.
 */
export function CheckInputMonitoring(): $CancellablePromise<boolean> {
    return $Call.ByID(3222937727);
}

/**
 * CheckScreenRecording checks whether macOS screen recording is authorized (needed by
 * screenshot translate; cross-platform: non-darwin returns true directly).
 */
export function CheckScreenRecording(): $CancellablePromise<boolean> {
    return $Call.ByID(3709400350);
}

/**
 * EmitHotkeysChanged is for outer callers (the hotkey manager) to broadcast the currently
 * active hotkey list.
 */
export function EmitHotkeysChanged(active: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2762446195, active);
}

/**
 * GetVersion returns the app version.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(240241073);
}

/**
 * OpenAccessibilitySettings opens the system accessibility settings pane (darwin only).
 */
export function OpenAccessibilitySettings(): $CancellablePromise<void> {
    return $Call.ByID(1595068374);
}

/**
 * OpenInputMonitoringSettings asks macOS to list Kai under Input Monitoring and opens that pane
 * (darwin only; a no-op elsewhere). The Settings page re-checks the state every 3 seconds.
 */
export function OpenInputMonitoringSettings(): $CancellablePromise<void> {
    return $Call.ByID(731115276);
}

/**
 * OpenScreenRecordingSettings pops the system "Screen Recording" permission dialog (darwin
 * only).
 */
export function OpenScreenRecordingSettings(): $CancellablePromise<void> {
    return $Call.ByID(61251697);
}

/**
 * ScreenshotOCR is screenshot OCR (no args, uses the default OCR engine, delegates to
 * translate.Service).
 */
export function ScreenshotOCR(): $CancellablePromise<model$0.OcrResult | null> {
    return $Call.ByID(3108408259);
}

/**
 * SetApp injects the app once it is ready (startup orchestration phase).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2741950910, app);
}

/**
 * SetUserAgent is called by the frontend at window startup, passing the WebView's
 * navigator.userAgent to the backend as the default User-Agent for global HTTP requests
 * (injected into each engine's http.Client via the useragent package).
 */
export function SetUserAgent(ua: string): $CancellablePromise<void> {
    return $Call.ByID(587101401, ua);
}

/**
 * TranslateMulti batch-translates (delegates to translate.Service, exposed to the frontend as
 * AppService.TranslateMulti).
 */
export function TranslateMulti(req: model$0.TranslateRequest): $CancellablePromise<model$0.TranslateMultiResult | null> {
    return $Call.ByID(787669562, req);
}
