// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigWrapper handles persistence and reads of UI config (language/theme/default
 * engine/hotkeys/TTS/exec keys), plus resolution and external queries of language/theme.
 * Engine config (Engines) is managed independently by EngineWrapper.
 * Only exposes RPCs — none of the wails lifecycle trio.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns the current config pointer.
 */
export function GetConfig(): $CancellablePromise<settings$0.Settings | null> {
    return $Call.ByID(651119548);
}

/**
 * GetLanguages returns the languages the source/target dropdowns offer (value=code,
 * name=display name): the SELECTABLE set — the recognized bare bases es / pt are left out.
 */
export function GetLanguages(lang: string): $CancellablePromise<$models.NamedItem[] | null> {
    return $Call.ByID(3807973897, lang);
}

/**
 * GetSystemTheme returns the actual theme (dark/light) resolved from the current system
 * appearance.
 * matchMedia('prefers-color-scheme') inside the Wails webview may be unreliable on macOS, so
 * the backend provides the single trusted source via application.Env.IsDarkMode().
 */
export function GetSystemTheme(): $CancellablePromise<string> {
    return $Call.ByID(1303942916);
}

/**
 * GetTheme returns the current theme config (may contain auto).
 */
export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(3923435619);
}

/**
 * SaveConfig persists UI config to settings.json; language/theme changes sync globally.
 */
export function SaveConfig(cfg: settings$0.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(1150430385, cfg);
}

/**
 * SetApp injects the app once it is ready.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(600301637, app);
}

/**
 * SetTheme persists the theme config.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(995726519, theme);
}

/**
 * SystemLanguages returns the language packs installed for macOS system translation
 * (Translation.framework).
 * darwin only; for non-darwin platforms see apple_langs_other.go.
 */
export function SystemLanguages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2181419198);
}

/**
 * Theme returns the user-configured theme (auto/light/dark, falling back to auto when
 * unconfigured).
 */
export function Theme(): $CancellablePromise<string> {
    return $Call.ByID(1167934511);
}
