// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineWrapper is the thin adapter over engine config: it holds registry + configstore +
 * settings + hotkey and is responsible for runtime registration/persistence of engine
 * enable/disable and for serving schemas. It only exposes RPCs — none of the wails
 * lifecycle trio.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveTranslateEngine returns the "current engine" name bound in the translate window's
 * result pane (issue #9, design §1): one more layer than PrimaryTranslateEngine — last-used.
 * lastUsed valid (kind=translate, enabled column=1, platform supported) -> it;
 * otherwise settings.default_engine valid -> it;
 * otherwise the first enabled translation engine (configstore id order);
 * none -> "".
 * lastUsed is the previously used engine persisted in the frontend's localStorage
 * (kai:translate:lastEngine); an empty string is equivalent to PrimaryTranslateEngine (the
 * degenerate case).
 * Resolution shares activeTranslateEngine with PrimaryTranslateEngine (no duplicate
 * enabled/translate/supported filtering); "enabled" likewise comes from configstore's
 * enabled column.
 */
export function ActiveTranslateEngine(lastUsed: string): $CancellablePromise<string> {
    return $Call.ByID(628453120, lastUsed);
}

/**
 * AddEngine adds a single engine config to config.db, returning the DB-assigned ID.
 */
export function AddEngine(cfg: engine$0.EngineConfig | null): $CancellablePromise<number> {
    return $Call.ByID(2510416615, cfg);
}

/**
 * CheckTesseract probes whether tesseract is installed locally, returning install state and
 * executable path, for the settings page to show the Tesseract engine's
 * "installed/not installed" hint.
 */
export function CheckTesseract(): $CancellablePromise<engine$0.TesseractStatus> {
    return $Call.ByID(2067219980);
}

/**
 * GetAllEngines returns "all" engines from config.db's engines table with their enabled
 * state.
 * List data comes straight from the database (configStore.LoadEngines) — never through a
 * settings copy and never merged with the code's KnownEngines — engine config is config.db's
 * independent data source, unrelated to the UI-preference settings.
 * Add/enable/delete all go through the form and their respective DB operations.
 * kind comes from the KnownEngines catalog (engine kind is registered in code, not stored in
 * the database).
 */
export function GetAllEngines(): $CancellablePromise<$models.AllEngineItem[] | null> {
    return $Call.ByID(191559056);
}

/**
 * GetEngineConfig returns one engine's full config by ID (including persisted
 * api_key/endpoint etc.), for the settings page's right-hand form to backfill stored values.
 * Returns nil when not found.
 */
export function GetEngineConfig(id: number): $CancellablePromise<engine$0.EngineConfig | null> {
    return $Call.ByID(250220986, id);
}

/**
 * GetEngineSchema returns the "real" config-field schema of the given engine, for the
 * frontend to render the right-hand form dynamically.
 */
export function GetEngineSchema(engineName: string): $CancellablePromise<engine$0.EngineSchema> {
    return $Call.ByID(3136113511, engineName);
}

/**
 * GetEngines returns all registered engines (translation + OCR) as (value, type name, type)
 * entries, ordered strictly by the auto-increment id of config.db's engines table (not the
 * code registration order).
 */
export function GetEngines(): $CancellablePromise<$models.EngineListItem[] | null> {
    return $Call.ByID(1488128365);
}

/**
 * GetKnownEngines returns the catalog of "addable" engines (from the code's KnownEngines),
 * for the settings page's add-form "engine type" dropdown. The list only renders existing DB
 * entries; the dropdown options must come from the code catalog so names are recognizable by
 * the Registry and translation actually works.
 */
export function GetKnownEngines(): $CancellablePromise<$models.EngineListItem[] | null> {
    return $Call.ByID(1073135640);
}

/**
 * GetOcrLangs returns the OCR-engine (vision / tesseract) language-code options, for the
 * frontend's OCR-specific UI to render the langs multi-select. Decoupled from Extra(JSON),
 * maintained solely in code.
 */
export function GetOcrLangs(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3491230379);
}

/**
 * PrimaryTranslateEngine returns the "primary translation engine" name the translate window
 * should bind on first paint. This is the authoritative implementation of the primary-engine
 * resolution rules (the backend's single source of truth; the frontend resolvePrimaryEngine
 * is its mirror, kept consistent by the divergence check in test (d)).
 * Resolution order: settings.default_engine valid (kind=translate, enabled, platform
 * supported) -> it; otherwise fall back to the first enabled translation engine
 * (configstore id order, same as GetEngines); none -> "".
 * "Invalid / disabled / unknown" all fall back silently — no error.
 * Note: "enabled" comes from configstore's enabled column (live), not the registry's
 * registration state — a disabled engine is not immediately unregistered from the registry,
 * and GetEngines()'s Supported only expresses platform support, which can't serve as the
 * enabled basis; hence the direct configStore.LoadEngines query here.
 */
export function PrimaryTranslateEngine(): $CancellablePromise<string> {
    return $Call.ByID(1132584400);
}

/**
 * RemoveEngine deletes a single engine config by ID.
 * System built-in engines (apple / vision) cannot be deleted: they are config-free and their
 * existence is guaranteed by code; deleting them would break OCR single-select / system
 * translation. The frontend already hides the delete button for builtin entries; this adds a
 * backend guard so other call paths can't delete them by mistake.
 */
export function RemoveEngine(id: number): $CancellablePromise<void> {
    return $Call.ByID(1575958516, id);
}

/**
 * SetApp injects the app once it is ready.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(248546961, app);
}

/**
 * ToggleEngineEnabled toggles a single engine's enabled/disabled state by ID.
 * When enabling (enabled=true), required params are validated; missing ones reject the
 * enable with a hint.
 */
export function ToggleEngineEnabled(id: number, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1976956865, id, enabled);
}

/**
 * UpdateEngineConfig updates all config fields of a single engine by ID.
 */
export function UpdateEngineConfig(cfg: engine$0.EngineConfig | null): $CancellablePromise<void> {
    return $Call.ByID(3464143975, cfg);
}
