// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryWrapper is the thin adapter over translation history: holds historystore.Store +
 * configstore, doing only RPC passthrough and DTO conversion.
 * Does not implement the wails lifecycle trio.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory clears all history.
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(2073293877);
}

/**
 * CountHistory returns the total history count matching the keyword, for the frontend's page
 * count.
 */
export function CountHistory(keyword: string): $CancellablePromise<number> {
    return $Call.ByID(534557787, keyword);
}

/**
 * DeleteHistory deletes one history entry.
 */
export function DeleteHistory(id: number): $CancellablePromise<void> {
    return $Call.ByID(3674865607, id);
}

/**
 * GetHistory queries translation history with pagination.
 */
export function GetHistory(keyword: string, offset: number, limit: number): $CancellablePromise<$models.HistoryItem[] | null> {
    return $Call.ByID(1672926790, keyword, offset, limit);
}
