// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LangPrefWrapper is the thin adapter over the language-variant preference store (issue #53):
 * RPC passthrough only, no wails lifecycle. The frontend feeds the store from its language
 * selects (Learn); everything else — qualifying detected languages at translation time, ending
 * the session on window close — happens in the backend and needs no binding.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Learn records an explicit language selection: picking a dialect (es-MX, pt-BR, pt-PT, ...) in
 * any language select makes it the preferred variant of its language for the rest of the window
 * session, so later auto-detected text in that language is qualified as the variant. Bases and
 * languages without dialects are ignored by the store, so the frontend passes every explicit
 * select change through — and only those: swapping the languages and loading saved defaults are
 * not selections and must never call it.
 */
export function Learn(lang: model$0.Language): $CancellablePromise<void> {
    return $Call.ByID(1546460697, lang);
}
