// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AllEngineItem is a settings-page "all configurable services" entry (enabled or not).
 */
export interface AllEngineItem {
    /**
     * Engine auto-increment primary key (0 for built-ins)
     */
    "id": number;

    /**
     * Engine identifier
     */
    "value": string;

    /**
     * Display name
     */
    "name": string;

    /**
     * translate | ocr
     */
    "kind": string;

    /**
     * Whether enabled
     */
    "enabled": boolean;

    /**
     * Whether the current platform supports it
     */
    "supported": boolean;

    /**
     * System built-in config-free engine (e.g. vision system OCR); cannot be deleted, but the switch can be toggled
     */
    "builtin": boolean;

    /**
     * TargetLanguages lists the selectable languages this engine can translate INTO (the
     * backend language capability registry, engine.SupportedTargets); the frontend disables every
     * other target option instead of keeping its own map. Empty for OCR engines. Source support
     * is not listed: every engine accepts every recognized source (variants alias to their base).
     */
    "target_languages": model$0.Language[] | null;
}

/**
 * EngineListItem backs the settings page's "engines" grouping: service names left, configs
 * right.
 * Kind distinguishes translate / ocr; the frontend groups and renders different markers
 * accordingly.
 */
export interface EngineListItem {
    /**
     * Engine identifier
     */
    "value": string;

    /**
     * Display name
     */
    "name": string;

    /**
     * translate | ocr
     */
    "kind": string;

    /**
     * Whether the current platform supports it (e.g. apple is darwin-only)
     */
    "supported": boolean;
}

/**
 * HistoryItem is a single history entry returned to the frontend (time as a millisecond
 * timestamp, engine ID resolved to a readable name).
 */
export interface HistoryItem {
    /**
     * History record auto-increment primary key
     */
    "id": number;

    /**
     * Source text
     */
    "text": string;

    /**
     * Translation result
     */
    "result": string;

    /**
     * Source language code
     */
    "from_lang": string;

    /**
     * Target language code
     */
    "to_lang": string;

    /**
     * Engine identifier used
     */
    "engine": string;

    /**
     * Whether it came from OCR recognition
     */
    "from_ocr": boolean;

    /**
     * Creation time (millisecond timestamp)
     */
    "created_at": number;
}

/**
 * NamedItem is an entry with a display name (for frontend dropdowns/lists).
 */
export interface NamedItem {
    /**
     * Option value (identifier)
     */
    "value": string;

    /**
     * Option display name
     */
    "name": string;
}
