// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationService wraps permission checks and safe sending for native desktop
 * notifications, so callers never bare-call the Wails notifications service and miss the
 * permission check (on macOS an unauthorized send fails silently and is undebuggable).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/services/notifications/models.js";

/**
 * Notify safely sends a notification: ensures authorization first; skips and logs when
 * unauthorized or denied. Send failures are also only logged, never propagated upward
 * (background flows like update checks must not be blocked by notification problems).
 */
export function Notify(opts: notifications$0.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByID(604523010, opts);
}
