// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TranslateWrapper is the thin adapter over translation / OCR: holds translate.Service,
 * doing only RPC passthrough.
 * Does not implement the wails lifecycle trio (startup orchestration is AppService's job).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * BackTranslate translates the displayed result back into the source language, to check it in the
 * user's own language (issue #56). req.Text is the result and req.From / req.To are already the
 * swapped pair. It never raises an error: the answer's status says how it ended, so a failure cannot
 * disturb the main result. It is cancelled with CancelTranslate(requestID, "").
 */
export function BackTranslate(req: model$0.TranslateRequest): $CancellablePromise<model$0.BackTranslateResult> {
    return $Call.ByID(2811488659, req);
}

/**
 * CancelTranslate cancels the running translation request requestID (issue #109), or only its
 * engine when engine is not empty; the other engines keep running. It reports whether it found
 * something still running, and returns false, without any error, for an unknown or finished
 * request or engine.
 */
export function CancelTranslate(requestID: string, engine: string): $CancellablePromise<boolean> {
    return $Call.ByID(3553365376, requestID, engine);
}

/**
 * CommitAutoHistory writes to the history what the automatic translation requestID produced, once
 * the text it was made for has stopped changing (issue #57). It returns how many results it handed
 * to the history, and writes nothing for a request a newer one replaced.
 */
export function CommitAutoHistory(requestID: string): $CancellablePromise<number> {
    return $Call.ByID(1462367678, requestID);
}

/**
 * CorrectSource corrects the grammar and word choice of text that just arrived, when the "correct
 * grammar and wording" setting is on and Apple's on-device model can run (issue #208). Every way
 * text arrives asks through this one call, right before PlanSourceSwitch, and translates the answer's
 * text; the answer never persists or teaches anything.
 */
export function CorrectSource(req: model$0.CorrectionRequest): $CancellablePromise<model$0.Correction> {
    return $Call.ByID(2205934651, req);
}

/**
 * CorrectionAvailability reports whether the correction can run on this Mac, and why not when it
 * cannot, so the toolbar checkbox can say so (issue #208).
 */
export function CorrectionAvailability(): $CancellablePromise<model$0.CorrectionAvailability> {
    return $Call.ByID(2513257435);
}

export function Ocr(req: model$0.OcrRequest): $CancellablePromise<model$0.OcrResult | null> {
    return $Call.ByID(1768998496, req);
}

/**
 * PlanSourceSwitch decides whether text that just arrived changes the language pair (issue #200):
 * the source follows the text and the old source replaces the target. Every way text arrives asks
 * through this one call; the answer is applied, never learned or persisted, by the window.
 */
export function PlanSourceSwitch(req: model$0.SourceSwitchRequest): $CancellablePromise<model$0.SourceSwitch> {
    return $Call.ByID(2226517286, req);
}

/**
 * ReportSourceSwitchSkipped writes the window's own reason for not switching (the frontend drops a
 * plan when the text or the pair changed while it was computed, or the language is not offered) to
 * the main log, next to the backend's decision line, so one file tells the whole story (issue #16).
 * The frontend's own log file was empty in practice, and the reason is a fixed word, never text.
 */
export function ReportSourceSwitchSkipped(reason: string): $CancellablePromise<void> {
    return $Call.ByID(947839581, reason);
}

/**
 * RetranslateWithContext translates a text again in a context the user described in the result
 * pane's chat (issue #48). The engine whose result is shown does it when it can follow a context;
 * otherwise the on-device model, then a configured cloud LLM, do (see translate.Service). It is
 * cancelled with CancelTranslate(requestID, "").
 */
export function RetranslateWithContext(req: model$0.ContextTranslateRequest): $CancellablePromise<model$0.ContextTranslateResult> {
    return $Call.ByID(968639356, req);
}

export function ScreenshotOCR(engineName: string): $CancellablePromise<model$0.OcrResult | null> {
    return $Call.ByID(3318430308, engineName);
}

/**
 * ScreenshotTranslate is the main screenshot-translate flow: region screenshot→system
 * OCR→multi-engine translation→delivered to the screenshot window.
 * session identifies the cache origin (events.ScreenshotSessionScreenshot /
 * ScreenshotSessionInput).
 */
export function ScreenshotTranslate(session: string): $CancellablePromise<model$0.ScreenshotResult | null> {
    return $Call.ByID(674436322, session);
}

export function Translate(req: model$0.TranslateRequest): $CancellablePromise<model$0.TranslateResult | null> {
    return $Call.ByID(207873806, req);
}

export function TranslateMulti(req: model$0.TranslateRequest): $CancellablePromise<model$0.TranslateMultiResult | null> {
    return $Call.ByID(2013479831, req);
}
