// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TranslateWrapper is the thin adapter over translation / OCR: holds translate.Service,
 * doing only RPC passthrough.
 * Does not implement the wails lifecycle trio (startup orchestration is AppService's job).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CancelTranslate cancels the running translation request requestID (issue #109), or only its
 * engine when engine is not empty; the other engines keep running. It reports whether it found
 * something still running, and returns false, without any error, for an unknown or finished
 * request or engine.
 */
export function CancelTranslate(requestID: string, engine: string): $CancellablePromise<boolean> {
    return $Call.ByID(3553365376, requestID, engine);
}

export function Ocr(req: model$0.OcrRequest): $CancellablePromise<model$0.OcrResult | null> {
    return $Call.ByID(1768998496, req);
}

export function ScreenshotOCR(engineName: string): $CancellablePromise<model$0.OcrResult | null> {
    return $Call.ByID(3318430308, engineName);
}

/**
 * ScreenshotTranslate is the main screenshot-translate flow: region screenshot→system
 * OCR→multi-engine translation→delivered to the screenshot window.
 * session identifies the cache origin (events.ScreenshotSessionScreenshot /
 * ScreenshotSessionInput).
 */
export function ScreenshotTranslate(session: string): $CancellablePromise<model$0.ScreenshotResult | null> {
    return $Call.ByID(674436322, session);
}

export function Translate(req: model$0.TranslateRequest): $CancellablePromise<model$0.TranslateResult | null> {
    return $Call.ByID(207873806, req);
}

export function TranslateMulti(req: model$0.TranslateRequest): $CancellablePromise<model$0.TranslateMultiResult | null> {
    return $Call.ByID(2013479831, req);
}
