// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowWrapper is a thin adapter: responsible for summoning each window (main window /
 * settings window).
 * Window handles are looked up on demand via the app reference, avoiding stale window
 * instances.
 * Only exposes the RPCs the frontend needs — none of the wails lifecycle trio.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * DisableRestoration opts win out of macOS's Secure State Restoration ("Resume", issue #163):
 * see docs/handoffs/163-brief.md. Must be called after the window's native handle exists
 * (win.NativeWindow() is non-nil only once WebviewWindow.Run() has executed) — wire it to
 * events.Common.WindowRuntimeReady, never at window-creation time, or it silently no-ops.
 */
export function DisableRestoration(win: application$0.Window): $CancellablePromise<void> {
    return $Call.ByID(3453614084, win);
}

/**
 * SetApp injects the app once it is ready.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1570579795, app);
}

/**
 * ShowScreenshotWindow summons the screenshot translate window (symmetric with
 * ShowTranslateWindow).
 * Note: main.go's EventWindowShow('screenshot') still goes through the standalone
 * showScreenshotWindow() package-level function; it can later be migrated here uniformly so
 * all window summons choke-point through WindowWrapper.
 */
export function ShowScreenshotWindow(): $CancellablePromise<void> {
    return $Call.ByID(3066686029);
}

/**
 * ShowSettings opens settings, in front of a pinned translate window.
 */
export function ShowSettings(): $CancellablePromise<void> {
    return $Call.ByID(2264317276);
}

/**
 * ShowTranslateWindow summons the translate window
 */
export function ShowTranslateWindow(): $CancellablePromise<void> {
    return $Call.ByID(4045388625);
}
