// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DNSConfig is a DNS resolver config.
 */
export interface DNSConfig {
    /**
     * Enabled is whether this DNS config is active.
     */
    "enabled": boolean;

    /**
     * Servers is the list of DNS server addresses.
     */
    "servers": string[] | null;
}

/**
 * ExecKeyConfig holds execution-type hotkeys: the program actively simulates pressing these
 * keys via robotgo to perform actions.
 * They are not part of mgr.Register (they are "pressed keys", not "listened-for keys").
 */
export interface ExecKeyConfig {
    /**
     * Copy is the copy key: the program simulates pressing it to perform the system copy
     * (e.g. macOS Cmd+C), then reads the clipboard to translate.
     */
    "copy": ExecKeyEntry;
}

/**
 * ExecKeyEntry is a single execution-type hotkey: the key the program actively simulates
 * pressing + whether it is enabled.
 */
export interface ExecKeyEntry {
    /**
     * Key is the key combination the program actively simulates pressing.
     */
    "key": string;

    /**
     * Enabled is whether this exec key is enabled.
     */
    "enabled": boolean;

    /**
     * Fallback: when simulated copy fails (empty clipboard / injection failure), whether to
     * retry with the system default copy key.
     * When on: if the custom copy key didn't take effect, automatically run the system-native
     * copy key once (macOS Cmd+C / elsewhere Ctrl+C) instead of giving up on copying.
     */
    "fallback": boolean;
}

/**
 * HotkeyEntry is a single registration-type hotkey: stores both the key combination and its
 * enabled state.
 * The previous struct stored only the key string with no per-item enabled state; it is now
 * split into Key (the combination; empty string = unset) and Enabled. Unset Key or disabled
 * means never registered.
 */
export interface HotkeyEntry {
    /**
     * Key is the key combination; an empty string means unset.
     */
    "key": string;

    /**
     * Enabled is whether this hotkey is enabled.
     */
    "enabled": boolean;
}

/**
 * HttpLogConfig is the HTTP request-log config (not yet synced to the frontend UI).
 */
export interface HttpLogConfig {
    /**
     * Enabled is whether HTTP request logging is on.
     */
    "enabled": boolean;

    /**
     * RetentionDays is the log retention in days.
     */
    "retention_days": number;
}

/**
 * LogConfig is the app runtime-log config (written only to settings.json, consumed by main's
 * logging module; not synced directly to the frontend UI).
 * Level supports debug / info / warn / error; cleanup policy is based on day-rotated log
 * files.
 */
export interface LogConfig {
    /**
     * Level is the log level: debug / info / warn / error (empty or invalid falls back to
     * info).
     */
    "level": string;

    /**
     * RetentionDays is how many days to keep log files (<=0 = never clean up).
     */
    "retention_days": number;

    /**
     * Compress is whether expired old log files are compressed to .gz (within the retention
     * window).
     */
    "compress": boolean;
}

/**
 * ProxyConfig is the network-proxy config (not yet synced to the frontend UI).
 */
export interface ProxyConfig {
    /**
     * Enabled is whether the proxy is on.
     */
    "enabled": boolean;

    /**
     * Protocol is the proxy protocol: http / https / socks5.
     */
    "protocol": string;

    /**
     * Host is the proxy host address.
     */
    "host": string;

    /**
     * Port is the proxy port.
     */
    "port": number;

    /**
     * Username is the proxy auth username (optional).
     */
    "username": string;

    /**
     * Password is the proxy auth password (optional).
     */
    "password": string;
}

/**
 * RegisteredHotkeyConfig holds registration-type global hotkeys (all listened to via
 * mgr.Register; fired when the user presses them).
 * Each hotkey is a HotkeyEntry with key and enabled state.
 */
export interface RegisteredHotkeyConfig {
    /**
     * Input is the summon-main-window hotkey (core feature, enabled by default).
     */
    "input": HotkeyEntry;

    /**
     * Screenshot is the screenshot-translate hotkey.
     */
    "screenshot": HotkeyEntry;
}

/**
 * Settings is the app settings (UI preferences only; engine config is stored independently
 * in config.db, not here).
 */
export interface Settings {
    /**
     * Language is the UI language: auto / zh-CN / en-US. New installs default to en-US;
     * auto follows the system language (a Chinese system selects Chinese, anything else English).
     * Note: this is the app's display language — separate from the translation languages
     * (model.Language: auto/zh/en/...). Two independent systems; never mix them.
     */
    "language": string;

    /**
     * Theme is the UI theme: auto / light / dark (auto follows the system appearance).
     */
    "theme": string;

    /**
     * DefaultTo is the default translation target language (e.g. zh / en). A fresh install starts
     * at DefaultTarget (en); a value persisted here is honored as saved (issue #44).
     */
    "default_to": string;

    /**
     * DefaultFrom is the default translation source language (auto = auto-detect).
     */
    "default_from": string;

    /**
     * DefaultEngine is the primary (default) translation engine identifier (an engine name
     * like "google"; an empty string means unset).
     * When unset / pointing at a missing or disabled engine, resolution falls back to the
     * first enabled translation engine.
     */
    "default_engine": string;

    /**
     * Hotkeys are registration-type global hotkeys (fired when the user presses them).
     */
    "hotkeys": RegisteredHotkeyConfig;

    /**
     * ExecKeys are execution-type hotkeys (the program actively simulates pressing them to
     * perform an action).
     */
    "execkeys": ExecKeyConfig;

    /**
     * AutoClipboard is the input-translate window's "auto-read clipboard and translate"
     * switch. When on, the frontend polls the system clipboard and fills + translates the
     * input on change; it also automatically disables the copy key (avoiding double
     * triggering), snapshotting its prior state in CopyKeySnapshot.
     */
    "auto_clipboard": boolean;

    /**
     * CopyKeySnapshot records the copy key's prior state (enabled/fallback) when
     * AutoClipboard is switched on, restoring from it when AutoClipboard is switched off;
     * nil when never enabled.
     */
    "copy_key_snapshot": ExecKeyEntry | null;

    /**
     * TTS is the text-to-speech config.
     */
    "tts": TTSConfig;

    /**
     * HttpLog is the HTTP request-log config (not yet synced to the frontend UI).
     */
    "http_log": HttpLogConfig;

    /**
     * Log is the app runtime-log config (level / cleanup / compression).
     */
    "log": LogConfig;

    /**
     * Proxy is the network-proxy config (not yet synced to the frontend UI).
     */
    "proxy": ProxyConfig;

    /**
     * Updater is the auto-update config (only user-decidable items; token/provider are fixed
     * in code).
     */
    "updater": UpdaterConfig;

    /**
     * AnalyticsEnabled is the anonymous usage-stats switch (off by default, opt-in). When
     * off, the PostHog client is never initialized and nothing is reported.
     * Both the config file and the frontend UI share this field (Go reads settings.json; the
     * frontend reads/writes via GetConfig/SaveConfig).
     */
    "analytics_enabled": boolean;

    /**
     * AnalyticsInstalled records whether app_installed was already sent (first-install event
     * reported once).
     */
    "analytics_installed": boolean;

    /**
     * DNSConfigs is the custom DNS resolver config list.
     */
    "dns_configs": DNSConfig[] | null;

    /**
     * TranslateWindowWidth/Height persist the input-translate window's last user-resized size
     * (issue #173 item 5), read back into WebviewWindowOptions.Width/Height at window
     * creation in main.go so a resize survives a relaunch. Zero means "never resized yet" —
     * main.go falls back to the hardcoded default in that case. Window size is a native
     * (Go-side) property, not frontend state, so unlike Theme/Language above this is written
     * directly by main.go's resize listener (debounced), not via SaveConfig/the frontend.
     * Scoped to the translate window only (the window users actually resize); the settings
     * and screenshot windows keep their fixed defaults — see docs/handoffs/173-brief.md.
     */
    "translate_window_width": number;
    "translate_window_height": number;
}

/**
 * TTSConfig is the text-to-speech config.
 */
export interface TTSConfig {
    /**
     * Engine is the TTS engine identifier (e.g. system).
     */
    "engine": string;

    /**
     * Speed is the speech-rate multiplier; 1.0 is normal speed.
     */
    "speed": number;
}

/**
 * UpdaterConfig holds auto-update config (only user-decidable items like Prerelease /
 * Source; token / provider / asset-matching rules are fixed in main.go's code, not
 * configured here).
 */
export interface UpdaterConfig {
    /**
     * Prerelease is whether pre-release updates may be detected.
     * When on: update checks include the GitHub repo's pre-release versions as candidates.
     */
    "prerelease": boolean;

    /**
     * Source selects the update-check source: empty / "github" / "cnb".
     *   - empty (default): current logic — auto-pick per UI language (English → GitHub,
     *     Chinese → CNB).
     *   - "github": force official GitHub only (with SHA256SUMS verification).
     *   - "cnb": force the CNB mirror only (needs cnbToken; anonymous 401 / unreachable
     *     network is treated as "no update").
     * Note: only affects the "check / download source" choice, not the updater's own install
     * behavior.
     */
    "source": string;
}
