package i18n

import (
	"encoding/json"
	"errors"
	"strings"
)

// sep is an invisible control character (unit separator U+001F) used to separate fields
// inside the frontend-parseable envelope; it is never shown to the user (invisible in
// message boxes and logs).
const sep = "\x1f"

// Error is an error type carrying an i18n key and named params, letting the frontend
// translate into its own language (decoupled from the backend language).
//
// Implements the error interface: Error() returns "translated text + envelope", where the
// envelope holds the key and params JSON.
// Wails serializes Error() and hands it to the frontend; the frontend extracts the key and
// params via ParseError, then translates with its own i18n;
// if the frontend lacks that key, it falls back to showing the envelope's translated text
// (generated by the backend in the current language).
//
// Note: persistence (history, notifications) and backend logs should use TranslateError to
// extract the envelope-free plain translated text, keeping the envelope out of persisted
// data.
type Error struct {
	Key    string
	Params map[string]any
	Err    error
}

// NewError builds an error carrying only an i18n key and params (no underlying error).
func NewError(key string, params ...any) *Error {
	return &Error{Key: key, Params: toParamMap(params)}
}

// Wrap combines an underlying error with an i18n key/params; Error() keeps the underlying
// error message.
func Wrap(err error, key string, params ...any) *Error {
	return &Error{Key: key, Params: toParamMap(params), Err: err}
}

func toParamMap(params []any) map[string]any {
	m := make(map[string]any)
	for i := 0; i+1 < len(params); i += 2 {
		if k, ok := params[i].(string); ok {
			m[k] = params[i+1]
		}
	}
	return m
}

func flatten(m map[string]any) []any {
	out := make([]any, 0, len(m)*2)
	for k, v := range m {
		out = append(out, k, v)
	}
	return out
}

// translated returns the envelope-free translated text (for logs, persistence,
// notifications, etc.).
func (e *Error) translated() string {
	msg := T(e.Key, flatten(e.Params)...)
	if e.Err != nil {
		return msg + ": " + e.Err.Error()
	}
	return msg
}

// Error returns "translated text + envelope"; the envelope holds the key and params JSON
// for the frontend to parse and translate itself.
func (e *Error) Error() string {
	payload, _ := json.Marshal(e.Params)
	return e.translated() + sep + e.Key + sep + string(payload)
}

// Unwrap supports errors.Is/As and error-chain traversal.
func (e *Error) Unwrap() error { return e.Err }

// TranslateError extracts the envelope-free translated text from any error, for logging and
// persistence.
// Non-*Error values return their Error() directly; nil returns an empty string.
func TranslateError(err error) string {
	if err == nil {
		return ""
	}
	if ie, ok := errors.AsType[*Error](err); ok {
		return ie.translated()
	}
	return err.Error()
}

// ParseError parses an error message sent by the backend (from Error()), extracting the i18n
// key and params.
// Without an envelope it returns ok=false; the caller should fall back to showing the raw
// text.
func ParseError(s string) (key string, params map[string]any, translated string, ok bool) {
	before, after, ok := strings.Cut(s, sep)
	if !ok {
		return "", nil, s, false
	}
	translated = before
	rest := after
	before0, after0, ok0 := strings.Cut(rest, sep)
	if !ok0 {
		return "", nil, s, false
	}
	key = before0
	payload := after0
	pm := map[string]any{}
	_ = json.Unmarshal([]byte(payload), &pm)
	return key, pm, translated, true
}
