package i18n

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The merged locale files (internal/i18n/locales/en-US.json, zh-CN.json) are generated by
// scripts/merge-go-i18n.sh from the sources in locales/split/, and every build regenerates them
// (issue #29). A key added to a merged file by hand is dropped by the next build, so the message it
// names then prints as its raw key in the log (this happened to the Alt-A decision log in #16).
// This fails when a merged file has a key that no split source defines, or the other way round.
func TestMergedLocalesMatchTheirSplitSources(t *testing.T) {
	for _, locale := range []string{"en-US", "zh-CN"} {
		merged := readKeys(t, filepath.Join("locales", locale+".json"))
		split := map[string]bool{}
		files, err := filepath.Glob(filepath.Join("locales", "split", locale, "*.json"))
		if err != nil || len(files) == 0 {
			t.Fatalf("no split sources for %s: %v", locale, err)
		}
		for _, f := range files {
			for k := range readKeys(t, f) {
				split[k] = true
			}
		}
		for k := range merged {
			if k != "_comment" && !split[k] {
				t.Errorf("%s: %q is in the merged file but in no split source; add it under locales/split/%s/ and run scripts/merge-go-i18n.sh (a build drops it otherwise)", locale, k, locale)
			}
		}
		for k := range split {
			if !merged[k] {
				t.Errorf("%s: %q is in a split source but missing from the merged file; run scripts/merge-go-i18n.sh", locale, k)
			}
		}
	}
}

func readKeys(t *testing.T, path string) map[string]bool {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		t.Fatalf("%s: %v", path, err)
	}
	keys := make(map[string]bool, len(m))
	for k := range m {
		keys[k] = true
	}
	return keys
}
