-- httplog database migration script (a dedicated migration file, separate from schema.sql)
-- Used only for "store compatibility": appending new columns / indexes to the existing
-- http_log table.
-- Table creation itself lives in schema.sql; this file only holds ALTERs / extra indexes.
-- Note: SQLite has no `ADD COLUMN IF NOT EXISTS`, so a repeated ALTER reports a
-- "duplicate column" error. At runtime (httplog.go's Migrate) that error is ignored to stay
-- idempotent — a second launch / already-migrated store simply skips, without error.
-- When adding new columns later, append one ALTER TABLE line here — no Go code changes.

-- Example (current schema matches the CREATE TABLE; no missing columns yet; format kept for
-- future extensions):
-- ALTER TABLE http_log ADD COLUMN new_field TEXT DEFAULT '';
