// Package historystore provides SQLite persistence for translation history.
// Database query code is auto-generated by sqlc from query.sql; this file provides DB
// lifecycle management and convenience wrappers (parameter adaptation, ErrNoRows
// normalization, etc.).
package historystore

import (
	"context"
	"database/sql"
	_ "embed"
	"errors"
	"fmt"
	"strings"
	"time"

	"cnb.cool/dtapp/kai/internal/i18n"
	"cnb.cool/dtapp/kai/internal/sqlite"
)

//go:embed schema.sql
var schemaSQL string

//go:embed migration.sql
var migrationSQL string

// Store wraps the history.db connection and the generated queries.
type Store struct {
	db *sql.DB
	*Queries
}

// Open opens (or creates) the SQLite history database and runs migrations.
// An empty path uses an in-memory database (:memory:), for tests only.
func Open(path string) (*Store, error) {
	if path == "" {
		path = ":memory:"
	}
	db, err := sql.Open("sqlite3", sqlite.BuildDSN(path))
	if err != nil {
		return nil, fmt.Errorf(i18n.T("err.historystore_open_db"), err, err)
	}
	db.SetMaxOpenConns(1) // SQLite single writer
	if err := db.Ping(); err != nil {
		db.Close()
		return nil, fmt.Errorf(i18n.T("err.historystore_ping"), err, err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if _, err := db.ExecContext(ctx, schemaSQL); err != nil {
		db.Close()
		return nil, fmt.Errorf(i18n.T("err.historystore_migrate"), err, err)
	}
	// Incremental migration: run migration.sql's ALTERs against old stores that exist but
	// lack columns.
	// SQLite has no ADD COLUMN IF NOT EXISTS; a repeated ALTER reports "duplicate column",
	// which is ignored here to stay idempotent (same as httplogstore's Migrate).
	for stmt := range strings.SplitSeq(migrationSQL, ";") {
		stmt = strings.TrimSpace(stmt)
		if stmt == "" {
			continue
		}
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			if !strings.Contains(err.Error(), "duplicate column") {
				db.Close()
				return nil, fmt.Errorf(i18n.T("err.historystore_migrate"), err, err)
			}
		}
	}
	return &Store{db: db, Queries: New(db)}, nil
}

// Close closes the database connection.
func (s *Store) Close() error {
	return s.db.Close()
}

// FindByKey finds a record with completely identical content (for dedupe); returns 0 when
// not found.
// Normalizes ErrNoRows from the generated query.
func (s *Store) FindByKey(ctx context.Context, text, fromLang, toLang string, engineID, fromOCR int64) (int64, error) {
	id, err := s.FindDuplicate(ctx, FindDuplicateParams{
		Text:     text,
		EngineID: engineID,
		FromLang: fromLang,
		ToLang:   toLang,
		FromOcr:  fromOCR,
	})
	if errors.Is(err, sql.ErrNoRows) {
		return 0, nil
	}
	return id, err
}

// QueryByKeyword searches history by keyword; an empty keyword returns everything, newest
// first.
func (s *Store) QueryByKeyword(ctx context.Context, keyword string, limit, offset int64) ([]History, error) {
	return s.QueryHistory(ctx, QueryHistoryParams{
		Column1: keyword,
		Limit:   limit,
		Offset:  offset,
	})
}

// CountByKeyword returns the number of history entries matching the keyword.
func (s *Store) CountByKeyword(ctx context.Context, keyword string) (int64, error) {
	return s.CountHistory(ctx, keyword)
}
