// Package doublecopy implements "translate when the user presses Cmd+C twice quickly" (issue #199).
//
// The pieces, each with one job:
//   - Detector (this file): the pure timing rule, fed one Event per Cmd+C key-down.
//   - Blocked (guard.go): the privacy checks that stop a secret from reaching a translation engine.
//   - Service (service.go): starts and stops the listener with the setting, polls the source, waits
//     for the pasteboard to really change, applies the guards and hands the text to Deliver.
//   - Source / Pasteboard (source.go): the platform boundary. macOS implements it in the Swift
//     bridge with a listen-only event tap on its own thread; every other OS reports unsupported.
//
// The text is not translated here. Deliver is the app's existing arrival path (the same
// EventInputFill the auto-clipboard branch emits), so the source-language switch of issue #200 and
// everything else that happens to arriving text applies unchanged.
package doublecopy

import "time"

// Window is how close two Cmd+C key-downs must be to count as a pair. A constant, not a setting
// (a settable window is a listed follow-up of issue #199).
const Window = 500 * time.Millisecond

// macOS virtual key code of the C key, and the CGEventFlags bits the chord is made of.
const (
	KeyCodeC uint16 = 8

	FlagShift   uint64 = 0x20000
	FlagControl uint64 = 0x40000
	FlagOption  uint64 = 0x80000
	FlagCommand uint64 = 0x100000
)

// Event is one Cmd+C key-down as the source saw it.
type Event struct {
	// At is a monotonic timestamp taken by the source when the key went down. The rule uses
	// these, not the time Kai polled, so a slow poll cannot stretch or squeeze the window.
	At      time.Duration
	KeyCode uint16
	Flags   uint64
	// Autorepeat is a repeat generated by a held key, not a new press.
	Autorepeat bool
	// Own marks a key Kai itself posted (the simulated copy of the copy-key hotkey).
	Own bool
	// FrontIsKai marks a copy made while Kai is the frontmost app (copying from Kai's own panes).
	FrontIsKai bool
	// ChangeCount is the pasteboard's change count when the key went down; 0 means unknown.
	ChangeCount int64
	// Bundle is the frontmost app's bundle identifier when the key went down.
	Bundle string
}

// IsCopyChord reports whether ev is a plain Cmd+C: the C key with Command held and no other
// modifier of Shift, Option or Control (Caps Lock, fn and the numeric-pad bit do not matter).
func IsCopyChord(ev Event) bool {
	const others = FlagShift | FlagControl | FlagOption
	return ev.KeyCode == KeyCodeC && ev.Flags&FlagCommand != 0 && ev.Flags&others == 0
}

// Detector applies the pair rule. The zero value is ready to use; it is not safe for concurrent
// use (Service serializes it).
//
// The rule: a press that follows the previous counted press by at most Window makes a pair and
// fires once. Further presses that each follow the one before within Window belong to the same
// burst and do not fire again; only a gap longer than Window ends the burst. Auto-repeats, Kai's
// own copies, copies made inside Kai and anything that is not a plain Cmd+C are not presses at all.
type Detector struct {
	last  time.Duration
	have  bool
	fired bool
}

// Feed reports whether ev is the second press of a quick pair that has not fired yet.
func (d *Detector) Feed(ev Event) bool {
	if ev.Own || ev.FrontIsKai || ev.Autorepeat || !IsCopyChord(ev) {
		return false
	}
	if !d.have || ev.At < d.last || ev.At-d.last > Window {
		// A first press: nothing to pair with, the burst (if any) is over, or the clock went back.
		d.have, d.last, d.fired = true, ev.At, false
		return false
	}
	d.last = ev.At
	if d.fired {
		return false
	}
	d.fired = true
	return true
}

// Reset forgets any pending press and burst.
func (d *Detector) Reset() { *d = Detector{} }
