// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    BackTranslateStatus,
    ContextTranslateStatus,
    CorrectionStatus,
    Language
} from "./models.js";

export type {
    BackTranslateResult,
    ContextTranslateRequest,
    ContextTranslateResult,
    Correction,
    CorrectionAvailability,
    CorrectionRequest,
    DictItem,
    OcrRegion,
    OcrRequest,
    OcrResult,
    ScreenshotResult,
    SourceSwitch,
    SourceSwitchRequest,
    TextChange,
    TranslateMultiResult,
    TranslateRequest,
    TranslateResult
} from "./models.js";
