// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DictItem is a dictionary entry
 */
export interface DictItem {
    /**
     * Word
     */
    "word": string;

    /**
     * Part of speech (e.g. n./v.)
     */
    "pos": string;

    /**
     * Definition
     */
    "explain": string;
}

/**
 * Language is a language code (ISO 639-1, or a BCP 47 dialect tag such as es-MX)
 */
export enum Language {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Translation language codes (Translate Language): used for translation requests/results,
     * engine calls, and history records.
     * Values are the short codes translation engines expect (e.g. zh/en/ja) or, for dialect
     * variants, BCP 47 tags (es-MX/pt-BR/pt-PT), completely unrelated to the UI language — never
     * mix with the UI locale above.
     *
     * Auto-detect source language
     */
    Auto = "auto",

    /**
     * Chinese
     */
    ZH = "zh",

    /**
     * English
     */
    EN = "en",

    /**
     * Japanese
     */
    JA = "ja",

    /**
     * Korean
     */
    KO = "ko",

    /**
     * French
     */
    FR = "fr",

    /**
     * German
     */
    DE = "de",

    /**
     * Spanish (recognized base of the Spanish dialects; not selectable)
     */
    ES = "es",

    /**
     * Spanish (Mexico)
     */
    ESMX = "es-MX",

    /**
     * Portuguese (recognized base of the Portuguese dialects; not selectable)
     */
    PT = "pt",

    /**
     * Portuguese (Brazil)
     */
    PTBR = "pt-BR",

    /**
     * Portuguese (Portugal)
     */
    PTPT = "pt-PT",

    /**
     * Russian
     */
    RU = "ru",
};

/**
 * OcrRegion is a single text region
 */
export interface OcrRegion {
    /**
     * Region text
     */
    "text": string;

    /**
     * Recognition confidence
     */
    "conf": number;

    /**
     * Region bounding box [x1,y1,x2,y2]
     */
    "box": number[] | null;
}

/**
 * OcrRequest is an OCR request
 */
export interface OcrRequest {
    /**
     * OCR engine identifier to use
     */
    "engine": string;

    /**
     * CorrectText is Vision's usesLanguageCorrection (language correction).
     * true = on (more accurate, the default); false = off (faster, lower chance of sporadic
     * hangs, slightly less accurate).
     * A pointer so "unset" can be distinguished from "false"; when unset, engines use the
     * default true.
     */
    "correct_text"?: boolean | null;

    /**
     * TimeoutSec is the Vision OCR timeout in seconds. <=0 lets engines use their own
     * defaults (vision defaults to 60s).
     */
    "timeout_sec"?: number;

    /**
     * RetryCount is the Vision OCR failure-fallback retry count (for transient rejections
     * like CRImageReaderError).
     * <=0 lets engines use the default 2 (only meaningful for vision).
     */
    "retry_count"?: number;
}

/**
 * OcrResult is an OCR result
 */
export interface OcrResult {
    /**
     * OCR engine identifier
     */
    "engine": string;

    /**
     * All recognized text
     */
    "text": string;

    /**
     * Per-region details
     */
    "regions": OcrRegion[] | null;
}

/**
 * ScreenshotResult is the full screenshot translate result, pushed to the screenshot
 * window via EventScreenshotOCR.
 */
export interface ScreenshotResult {
    /**
     * Region screenshot PNG as a base64 data URL (frontend renders <img> directly)
     */
    "image": string;

    /**
     * Source text recognized by OCR
     */
    "text": string;

    /**
     * Per-engine translations
     */
    "translations": TranslateResult[] | null;

    /**
     * Requested target language (each translation carries its own To, which the same-language guard may have flipped, issue #44)
     */
    "to": Language;

    /**
     * Flow failure reason (when non-empty the frontend stops spinning and shows the error)
     */
    "error": string;
}

/**
 * TranslateMultiResult confirms the start of a multi-engine parallel translation; Count is
 * the number of engines started.
 * Actual results stream to the frontend one by one via the EventTranslateResult event.
 */
export interface TranslateMultiResult {
    /**
     * Number of engines started
     */
    "count": number;

    /**
     * Initial result set (including engine placeholders)
     */
    "results": TranslateResult[] | null;
}

/**
 * TranslateRequest is the unified translation request
 */
export interface TranslateRequest {
    /**
     * Source text to translate
     */
    "text": string;

    /**
     * Source language (auto = auto-detect)
     */
    "from": Language;

    /**
     * Target language
     */
    "to": Language;

    /**
     * Translation engine identifier to use
     */
    "engine": string;
}

/**
 * TranslateResult is a single translation result
 */
export interface TranslateResult {
    /**
     * Translation engine identifier
     */
    "engine": string;

    /**
     * The actually detected source language
     */
    "from": Language;

    /**
     * Target language the result was translated into (the fallback target when the same-language guard flipped the requested one, issue #44)
     */
    "to": Language;

    /**
     * Source text
     */
    "text": string;

    /**
     * Translation
     */
    "result": string;

    /**
     * Pronunciation/phonetics
     */
    "phonetic": string;

    /**
     * Dictionary detail entries
     */
    "dict": DictItem[] | null;

    /**
     * Whether it came from OCR recognition
     */
    "from_ocr": boolean;

    /**
     * Sanitized engine error on failure (issues #42, #96; empty on success)
     */
    "error"?: string;

    /**
     * Engine failure category, one of the ErrorKind* values (issues #42, #96)
     */
    "error_kind"?: string;
}
