// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackTranslateResult is the answer to translate.Service.BackTranslate: the displayed result
 * translated back into the source language, to check it in the user's own language. It is display
 * only. A failure carries no engine text, only the status.
 */
export interface BackTranslateResult {
    "status": BackTranslateStatus;
    "result": string;
    "engine": string;
    "request_id": string;
}

/**
 * BackTranslateStatus says how a back-translation ended (issue #56).
 */
export enum BackTranslateStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BackTranslateOK = "ok",

    /**
     * the user cancelled it, or a newer one replaced it
     */
    BackTranslateCancelled = "cancelled",

    /**
     * there is nothing to show: same language, or an empty answer
     */
    BackTranslateSkipped = "skipped",
    BackTranslateFailed = "failed",
};

/**
 * ContextTranslateRequest asks for a new translation of Text in a context the user described
 * (issue #48). Engine is the engine whose result is shown; Previous is that engine's translation,
 * the one the user says is wrong; Context is what the user has told the translator so far, oldest
 * message first (kept across texts until cleared).
 */
export interface ContextTranslateRequest {
    "text": string;
    "from": Language;
    "to": Language;
    "engine": string;
    "previous": string;
    "context": string[] | null;
    "request_id"?: string;
}

/**
 * ContextTranslateResult is the answer to a ContextTranslateRequest. Engine names the engine that
 * produced Result; Fallback is true when it is not the one the request named (that one cannot
 * follow a context). Reason, when the status is unavailable, is the on-device model's availability
 * reason (an engine.CorrectionStatus value) or "none_available"; the UI words it.
 */
export interface ContextTranslateResult {
    "status": ContextTranslateStatus;
    "result": string;
    "engine": string;
    "fallback": boolean;
    "reason": string;
    "error": string;
    "request_id": string;
}

/**
 * ContextTranslateStatus says how a context retranslation ended.
 */
export enum ContextTranslateStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContextTranslateOK = "ok",
    ContextTranslateCancelled = "cancelled",

    /**
     * no engine can follow a context; Reason says why
     */
    ContextTranslateUnavailable = "unavailable",
    ContextTranslateFailed = "failed",

    /**
     * the request carried no context message
     */
    ContextTranslateNoContext = "no_context",
};

/**
 * Correction is the answer to a CorrectionRequest. When Corrected, Text is the corrected text the
 * caller translates, Original the text as it arrived (kept so it can be restored in one click) and
 * Changes what differs, computed in Go and never by the model. Otherwise Text is the text as it
 * arrived and Changes is empty. Language is the language the text was corrected in (a variant the
 * dropdowns offer), empty when nothing was attempted. Reason carries the provider's availability
 * reason when Status is unavailable (the UI words it).
 */
export interface Correction {
    "corrected": boolean;
    "status": CorrectionStatus;
    "reason": string;
    "text": string;
    "original": string;
    "language": Language;
    "changes": TextChange[] | null;
}

/**
 * CorrectionAvailability tells the UI whether the correction can run at all on this machine, and
 * when it cannot, why (Reason is an engine.CorrectionStatus value the UI words).
 */
export interface CorrectionAvailability {
    "available": boolean;
    "reason": string;
}

/**
 * CorrectionRequest asks translate.Service.CorrectSource to correct the grammar and word choice of
 * text that has just arrived (issue #208): the text, the source language the window shows, and
 * optionally a detection the caller already holds (the one a #161 result carried).
 */
export interface CorrectionRequest {
    "text": string;
    "from": Language;
    "detected": Language;
}

/**
 * CorrectionStatus says why a CorrectionRequest was answered the way it was. Only Corrected means
 * the text changed; every other value is "translate the text as it came", and tells a test (and a
 * log line) which rule decided.
 */
export enum CorrectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * the text was changed
     */
    CorrectionCorrected = "corrected",

    /**
     * the model found nothing to fix
     */
    CorrectionUnchanged = "unchanged",

    /**
     * the setting is off
     */
    CorrectionOff = "off",

    /**
     * the source is Auto: no language to correct in
     */
    CorrectionAutoSource = "auto_source",

    /**
     * fewer than 8 code points
     */
    CorrectionTooShort = "too_short",

    /**
     * more than the model is asked to read in one go
     */
    CorrectionTooLong = "too_long",

    /**
     * no provider, or it reports it cannot run
     */
    CorrectionUnavailable = "unavailable",

    /**
     * the provider errored, refused or timed out
     */
    CorrectionFailed = "failed",

    /**
     * the output failed a guard
     */
    CorrectionRejected = "rejected",
};

/**
 * DictItem is a dictionary entry
 */
export interface DictItem {
    /**
     * Word
     */
    "word": string;

    /**
     * Part of speech (e.g. n./v.)
     */
    "pos": string;

    /**
     * Definition
     */
    "explain": string;
}

/**
 * Language is a language code (ISO 639-1, or a BCP 47 dialect tag such as es-MX)
 */
export enum Language {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Translation language codes (Translate Language): used for translation requests/results,
     * engine calls, and history records.
     * Values are the short codes translation engines expect (e.g. zh/en/ja) or, for dialect
     * variants, BCP 47 tags (es-MX/pt-BR/pt-PT), completely unrelated to the UI language — never
     * mix with the UI locale above.
     *
     * Auto-detect source language
     */
    Auto = "auto",

    /**
     * Chinese
     */
    ZH = "zh",

    /**
     * English
     */
    EN = "en",

    /**
     * Japanese
     */
    JA = "ja",

    /**
     * Korean
     */
    KO = "ko",

    /**
     * French
     */
    FR = "fr",

    /**
     * German
     */
    DE = "de",

    /**
     * Spanish (recognized base of the Spanish dialects; not selectable)
     */
    ES = "es",

    /**
     * Spanish (Mexico)
     */
    ESMX = "es-MX",

    /**
     * Portuguese (recognized base of the Portuguese dialects; not selectable)
     */
    PT = "pt",

    /**
     * Portuguese (Brazil)
     */
    PTBR = "pt-BR",

    /**
     * Portuguese (Portugal)
     */
    PTPT = "pt-PT",

    /**
     * Russian
     */
    RU = "ru",
};

/**
 * OcrRegion is a single text region
 */
export interface OcrRegion {
    /**
     * Region text
     */
    "text": string;

    /**
     * Recognition confidence
     */
    "conf": number;

    /**
     * Region bounding box [x1,y1,x2,y2]
     */
    "box": number[] | null;
}

/**
 * OcrRequest is an OCR request
 */
export interface OcrRequest {
    /**
     * OCR engine identifier to use
     */
    "engine": string;

    /**
     * CorrectText is Vision's usesLanguageCorrection (language correction).
     * true = on (more accurate, the default); false = off (faster, lower chance of sporadic
     * hangs, slightly less accurate).
     * A pointer so "unset" can be distinguished from "false"; when unset, engines use the
     * default true.
     */
    "correct_text"?: boolean | null;

    /**
     * TimeoutSec is the Vision OCR timeout in seconds. <=0 lets engines use their own
     * defaults (vision defaults to 60s).
     */
    "timeout_sec"?: number;

    /**
     * RetryCount is the Vision OCR failure-fallback retry count (for transient rejections
     * like CRImageReaderError).
     * <=0 lets engines use the default 2 (only meaningful for vision).
     */
    "retry_count"?: number;
}

/**
 * OcrResult is an OCR result
 */
export interface OcrResult {
    /**
     * OCR engine identifier
     */
    "engine": string;

    /**
     * All recognized text
     */
    "text": string;

    /**
     * Per-region details
     */
    "regions": OcrRegion[] | null;
}

/**
 * ScreenshotResult is the full screenshot translate result, pushed to the screenshot
 * window via EventScreenshotOCR.
 */
export interface ScreenshotResult {
    /**
     * Region screenshot PNG as a base64 data URL (frontend renders <img> directly)
     */
    "image": string;

    /**
     * Source text recognized by OCR
     */
    "text": string;

    /**
     * Per-engine translations
     */
    "translations": TranslateResult[] | null;

    /**
     * Requested target language
     */
    "to": Language;

    /**
     * Flow failure reason (when non-empty the frontend stops spinning and shows the error)
     */
    "error": string;

    /**
     * RequestID names this run of the screenshot flow (issue #109), on every push of the run. The
     * progress event is a broadcast that carries no window, so the screenshot window adopts its
     * request id from these pushes and ignores progress events of any other request.
     */
    "request_id": string;
}

/**
 * SourceSwitch is the answer to a SourceSwitchRequest. When Switched, From is the language the text
 * is in (a variant the dropdown offers) and To is the old source, which replaces the old target;
 * otherwise the pair stays as it is and From / To are empty. Reason says why (issue #16), so a
 * "no switch" is never silent: one of the SwitchReason constants.
 */
export interface SourceSwitch {
    "switched": boolean;
    "from": Language;
    "to": Language;
    "reason": string;
}

/**
 * SourceSwitchRequest asks translate.Service.PlanSourceSwitch whether text that arrived should
 * change the language pair (issue #200): the text, the pair the window shows now, and optionally a
 * detection the caller already holds (the one a translation result carried, issue #161).
 */
export interface SourceSwitchRequest {
    "text": string;
    "from": Language;
    "to": Language;
    "detected": Language;
}

/**
 * TextChange is one place where a correction changed the text: Before is the words as they were
 * written, After the words that replaced them. Either can carry a neighbouring word for context
 * (a pure insertion is shown as "casa" -> "casa de"), never more.
 */
export interface TextChange {
    "before": string;
    "after": string;
}

/**
 * TranslateMultiResult confirms the start of a multi-engine parallel translation; Count is
 * the number of engines started.
 * Actual results stream to the frontend one by one via the EventTranslateResult event.
 */
export interface TranslateMultiResult {
    /**
     * Number of engines started
     */
    "count": number;

    /**
     * Initial result set (including engine placeholders)
     */
    "results": TranslateResult[] | null;

    /**
     * RequestID is the request's id: the caller's TranslateRequest.RequestID echoed back, or the
     * one the backend generated when none was sent (issue #109).
     */
    "request_id": string;

    /**
     * Engines lists the engines actually started (never null). The request is over when each of
     * them has reported once (result, failure or cancel); the frontend settles from this list,
     * not from its own view of which engines are enabled (issue #109).
     */
    "engines": string[] | null;
}

/**
 * TranslateRequest is the unified translation request
 */
export interface TranslateRequest {
    /**
     * Source text to translate
     */
    "text": string;

    /**
     * Source language (auto = auto-detect)
     */
    "from": Language;

    /**
     * Target language
     */
    "to": Language;

    /**
     * Translation engine identifier to use
     */
    "engine": string;

    /**
     * RequestID names the request (issue #109). The frontend generates it before the call, because
     * a fast engine can emit its result before the binding call returns, so an id handed back by
     * the call would race the first event. It tags every event of the request and is what
     * CancelTranslate takes. Empty: the backend generates one.
     */
    "request_id"?: string;
}

/**
 * TranslateResult is a single translation result
 */
export interface TranslateResult {
    /**
     * Translation engine identifier
     */
    "engine": string;

    /**
     * The actually detected source language
     */
    "from": Language;

    /**
     * Target language (always the one requested)
     */
    "to": Language;

    /**
     * Source text
     */
    "text": string;

    /**
     * Translation
     */
    "result": string;

    /**
     * Pronunciation/phonetics
     */
    "phonetic": string;

    /**
     * Dictionary detail entries
     */
    "dict": DictItem[] | null;

    /**
     * Whether it came from OCR recognition
     */
    "from_ocr": boolean;

    /**
     * Result is the source text, not a translation: source and target are the same language (issue #80; set by the translate service only, never by an engine)
     */
    "identity"?: boolean;

    /**
     * Sanitized engine error on failure (issues #42, #96; empty on success)
     */
    "error"?: string;

    /**
     * Engine failure category, one of the ErrorKind* values (issues #42, #96)
     */
    "error_kind"?: string;

    /**
     * The request this result belongs to (issue #109); the frontend ignores results of any other request
     */
    "request_id"?: string;

    /**
     * Cancelled marks an engine the user cancelled (issue #109). It is a flag beside Error, not a
     * kind of it: a cancelled payload has no Error and no ErrorKind, and it is never a failure.
     * Result may hold a partial translation (the contract chunked translation, #84, fills).
     */
    "cancelled"?: boolean;

    /**
     * DetectedFrom is the auto-detected language a translation was made from, the same qualified
     * value as From (issue #161; set by the translate service only, never by an engine, like
     * Identity). It is set when an auto request's engine detected a recognized language, and when
     * the service corrected a pinned source because the text was in another language. It is empty
     * otherwise: on an identity result, when a pin stood, and when nothing usable was detected.
     * The translate window shows it as a note.
     */
    "detected_from"?: Language;
}
