// Package configstore provides SQLite persistence for the app's configuration data.
// Database query code is auto-generated by sqlc from query.sql; this file provides DB
// lifecycle management and the type conversion between engine config and the database
// model.
package configstore

import (
	"context"
	"database/sql"
	_ "embed"
	"errors"
	"fmt"
	"strings"
	"time"

	"cnb.cool/dtapp/kai/internal/engine"
	"cnb.cool/dtapp/kai/internal/i18n"
	"cnb.cool/dtapp/kai/internal/sqlite"
)

//go:embed schema.sql
var schemaSQL string

// Store wraps the config.db connection and the generated queries.
type Store struct {
	db *sql.DB
	*Queries
}

// Open opens (or creates) the SQLite config database and runs migrations.
func Open(path string) (*Store, error) {
	db, err := sql.Open("sqlite3", sqlite.BuildDSN(path))
	if err != nil {
		return nil, fmt.Errorf(i18n.T("err.configstore_open_db"), err, err)
	}
	pragmas := []string{
		"PRAGMA journal_mode=WAL",
		"PRAGMA busy_timeout=5000",
		"PRAGMA foreign_keys=ON",
	}
	for _, p := range pragmas {
		if _, err := db.Exec(p); err != nil {
			db.Close()
			return nil, fmt.Errorf(i18n.T("err.configstore_pragma"), p, err)
		}
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if _, err := db.ExecContext(ctx, schemaSQL); err != nil {
		db.Close()
		return nil, fmt.Errorf(i18n.T("err.configstore_migrate"), err, err)
	}
	s := &Store{db: db, Queries: New(db)}
	// One-time migration: encrypt historically plaintext credentials (old data without the
	// prefix); already-encrypted (prefixed) rows are skipped.
	if err := s.MigrateSecrets(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf(i18n.T("err.configstore_migrate_secrets"), err, err)
	}
	// One-time migration: engine identifier system → apple (naming consistency, symmetric
	// with vision).
	// Rows in the old store's engines table with engine='system' need updating to 'apple';
	// idempotent and safe to call repeatedly.
	if err := s.MigrateEngineNames(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf(i18n.T("err.configstore_migrate_engine_names"), err, err)
	}
	return s, nil
}

// MigrateEngineNames renames rows with engine='system' to 'apple' in the existing engines
// table.
// Historical versions used "system" as the macOS system translation engine identifier, now
// unified to "apple" (symmetric with "vision").
// Idempotent: no effect on stores already using 'apple'.
func (s *Store) MigrateEngineNames(ctx context.Context) error {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := s.RenameEngineByName(ctx, RenameEngineByNameParams{
		Engine:   "apple",  // New identifier (SET engine = ?)
		Engine_2: "system", // Old identifier (WHERE engine = ?)
	}); err != nil {
		return fmt.Errorf(i18n.T("err.configstore_rename_engine"), err, err)
	}
	return nil
}

// MigrateSecrets encrypts and writes back any api_key/secret in the engines table that is
// still plaintext; already-encrypted (cipherPrefix-bearing) records are left unchanged.
// Idempotent, safe to call repeatedly.
func (s *Store) MigrateSecrets(ctx context.Context) error {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	rows, err := s.LoadEngines(ctx)
	if err != nil {
		return err
	}
	for _, r := range rows {
		needUpdate := false
		apiKey := r.ApiKey
		secret := r.Secret
		if r.ApiKey != "" && !strings.HasPrefix(r.ApiKey, cipherPrefix) {
			if enc, e := EncryptSecret(r.ApiKey); e == nil {
				apiKey = enc
				needUpdate = true
			}
		}
		if r.Secret != "" && !strings.HasPrefix(r.Secret, cipherPrefix) {
			if enc, e := EncryptSecret(r.Secret); e == nil {
				secret = enc
				needUpdate = true
			}
		}
		if !needUpdate {
			continue
		}
		if err := s.UpdateEngineByID(ctx, UpdateEngineByIDParams{
			Engine:   r.Engine,
			Enabled:  r.Enabled,
			ApiKey:   apiKey,
			Secret:   secret,
			Extra:    r.Extra,
			Endpoint: r.Endpoint,
			ID:       r.ID,
		}); err != nil {
			return err
		}
	}
	return nil
}

// Close closes the database connection.
func (s *Store) Close() error {
	return s.db.Close()
}

// ---- Single-engine operations (replacing the all-at-once SaveEngineConfigs) ----

// InsertEngineConfig inserts one engine config, returning the auto-increment ID assigned by
// SQLite.
// api_key / secret are encrypted before persisting (sensitive fields never stored in
// plaintext).
func (s *Store) InsertEngineConfig(ctx context.Context, e *engine.EngineConfig) (int64, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	apiKey, err := EncryptSecret(e.APIKey)
	if err != nil {
		return 0, fmt.Errorf("%s: %w", i18n.T("err.configstore_encrypt_apikey"), err)
	}
	secret, err := EncryptSecret(e.Secret)
	if err != nil {
		return 0, fmt.Errorf("%s: %w", i18n.T("err.configstore_encrypt_secret"), err)
	}
	id, err := s.InsertEngine(ctx, InsertEngineParams{
		Engine:   e.Engine,
		Enabled:  boolToInt64(e.Enabled),
		ApiKey:   apiKey,
		Secret:   secret,
		Extra:    e.Extra,
		Endpoint: e.Endpoint,
	})
	if err != nil {
		return 0, fmt.Errorf(i18n.T("err.configstore_insert_engine"), e.Engine, err, e.Engine, err)
	}
	e.ID = id
	return id, nil
}

// UpdateEngineConfig updates all fields of a single engine by ID.
// api_key / secret are encrypted before persisting.
func (s *Store) UpdateEngineConfig(ctx context.Context, e *engine.EngineConfig) error {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	apiKey, err := EncryptSecret(e.APIKey)
	if err != nil {
		return fmt.Errorf("%s: %w", i18n.T("err.configstore_encrypt_apikey"), err)
	}
	secret, err := EncryptSecret(e.Secret)
	if err != nil {
		return fmt.Errorf("%s: %w", i18n.T("err.configstore_encrypt_secret"), err)
	}
	return s.UpdateEngineByID(ctx, UpdateEngineByIDParams{
		Engine:   e.Engine,
		Enabled:  boolToInt64(e.Enabled),
		ApiKey:   apiKey,
		Secret:   secret,
		Extra:    e.Extra,
		Endpoint: e.Endpoint,
		ID:       e.ID,
	})
}

// SetEngineEnabled toggles a single engine's enabled/disabled state by ID.
func (s *Store) SetEngineEnabled(ctx context.Context, id int64, enabled bool) error {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	return s.UpdateEngineEnabled(ctx, UpdateEngineEnabledParams{
		ID:      id,
		Enabled: boolToInt64(enabled),
	})
}

// DeleteEngineByID deletes a single engine by ID.
func (s *Store) DeleteEngineByID(ctx context.Context, id int64) error {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	return s.Queries.DeleteEngineByID(ctx, id)
}

// GetEngineByName queries a single engine config by name; returns (nil, nil) when not found.
func (s *Store) GetEngineByName(ctx context.Context, name string) (*engine.EngineConfig, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	row, err := s.Queries.GetEngineByName(ctx, name)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf(i18n.T("err.configstore_get_engine_name"), err, err)
	}
	return engineConfigFromDB(row), nil
}

// GetEngineByID queries a single engine config by ID; returns (nil, nil) when not found.
func (s *Store) GetEngineByID(ctx context.Context, id int64) (*engine.EngineConfig, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	row, err := s.Queries.GetEngineByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf(i18n.T("err.configstore_get_engine_id"), err, err)
	}
	return engineConfigFromDB(row), nil
}

// engineConfigFromDB converts the sqlc-generated Engine model into the business-layer
// EngineConfig.
// api_key / secret are decrypted from the stored ciphertext into plaintext (for engine calls
// and the frontend form backfill).
func engineConfigFromDB(e Engine) *engine.EngineConfig {
	apiKey, _ := DecryptSecret(e.ApiKey)
	secret, _ := DecryptSecret(e.Secret)
	return &engine.EngineConfig{
		ID:       e.ID,
		Engine:   e.Engine,
		Enabled:  e.Enabled != 0,
		APIKey:   apiKey,
		Secret:   secret,
		Extra:    e.Extra,
		Endpoint: e.Endpoint,
	}
}

// ---- Initialization ----

// InitDefaultEngines writes the default engine list when config.db is empty.
func (s *Store) InitDefaultEngines(ctx context.Context, defaults []*engine.EngineConfig) error {
	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	for _, e := range defaults {
		if _, err := s.InsertEngineConfig(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

// ---- Type conversion & lookups ----

// EnginesToConfig converts database Engine models into business-layer engine.EngineConfig.
// api_key / secret are decrypted from the stored ciphertext into plaintext.
func EnginesToConfig(rows []Engine) []*engine.EngineConfig {
	out := make([]*engine.EngineConfig, 0, len(rows))
	for _, r := range rows {
		apiKey, _ := DecryptSecret(r.ApiKey)
		secret, _ := DecryptSecret(r.Secret)
		out = append(out, &engine.EngineConfig{
			ID:       r.ID,
			Engine:   r.Engine,
			Enabled:  r.Enabled != 0,
			APIKey:   apiKey,
			Secret:   secret,
			Extra:    r.Extra,
			Endpoint: r.Endpoint,
		})
	}
	return out
}

// EngineIDByName looks up an ID by name in an engine-config list (kept for in-memory
// scenarios).
func EngineIDByName(engs []*engine.EngineConfig, name string) int64 {
	for _, e := range engs {
		if e.Engine == name {
			return e.ID
		}
	}
	return 0
}

// EngineNameByID looks up a name by ID in an engine-config list (kept for in-memory
// scenarios).
func EngineNameByID(engs []*engine.EngineConfig, id int64) string {
	for _, e := range engs {
		if e.ID == id {
			return e.Engine
		}
	}
	return ""
}

func boolToInt64(b bool) int64 {
	if b {
		return 1
	}
	return 0
}
