// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineConfig holds one engine's credentials/config (single source of truth; the settings
 * package reuses this type so engine and settings never import each other in a cycle).
 * ID is the config.db primary key: 0 means not yet persisted (newly added by the frontend),
 * >0 means an existing row (frontend updates/deletes key off it).
 * Engine config has moved to config.db persistence, no longer settings.json (hence no
 * mapstructure tags; json tags kept for frontend RPC).
 */
export interface EngineConfig {
    /**
     * Auto-increment primary key of the engine config
     */
    "id": number;

    /**
     * Engine identifier
     */
    "engine": string;

    /**
     * Whether enabled
     */
    "enabled": boolean;

    /**
     * API token ID (used as the auth credential)
     */
    "api_key"?: string;

    /**
     * API token secret (used as the signing key)
     */
    "secret"?: string;

    /**
     * Extra extension config (JSON string)
     */
    "extra"?: string;

    /**
     * Custom endpoint URL (optional)
     */
    "endpoint"?: string;
}

/**
 * EngineFieldSchema describes a single config field an engine needs.
 * Field maps to EngineConfig's real field name (api_key / secret / endpoint / extra), so the
 * frontend reads/writes the corresponding field directly instead of forcing every engine
 * through the same one-size-fits-all form.
 */
export interface EngineFieldSchema {
    /**
     * Target field: api_key / secret / endpoint / extra
     */
    "field": string;

    /**
     * i18n key (frontend reads settings.engine_field.<name>)
     */
    "label_key": string;

    /**
     * i18n key (frontend reads settings.engine_ph.<name>; may be empty)
     */
    "placeholder_key": string;

    /**
     * string / secret
     */
    "type": EngineFieldType;

    /**
     * Structured-control override (ocr_*); empty renders per Type
     */
    "widget": FieldWidget;

    /**
     * Whether required when enabling the engine
     */
    "required": boolean;

    /**
     * Real default for optional URL/address fields; the frontend pre-fills the display when empty
     */
    "default": string;

    /**
     * Optional enum values (e.g. tesseract codes chi_sim/eng). When set, the frontend renders a multi-select whose values are joined with "+" into the field
     */
    "options": string[] | null;

    /**
     * Optional: i18n key for the hint text below the field
     */
    "hint_key": string;
}

/**
 * EngineFieldType is a config-field type (the frontend renders different controls per type).
 */
export enum EngineFieldType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * FieldString is plain text.
     */
    FieldString = "string",

    /**
     * FieldSecret is sensitive (password box).
     */
    FieldSecret = "secret",
};

/**
 * EngineKind is the engine kind: translation or OCR.
 */
export enum EngineKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindTranslator is a translation engine.
     */
    KindTranslator = "translate",

    /**
     * KindOCR is an OCR engine.
     */
    KindOCR = "ocr",
};

/**
 * EngineSchema is an engine's full set of config fields (order = render order).
 */
export interface EngineSchema {
    /**
     * Kind is the engine kind (translate / ocr), single source of truth; the frontend
     * distinguishes rendering by it, replacing the scattered AllEngineItem.kind checks.
     */
    "kind": EngineKind;

    /**
     * Builtin marks a system built-in engine (e.g. apple system translation / vision system
     * OCR): nothing to configure, cannot be removed. The frontend renders a uniform
     * "system built-in" status card from this, replacing per-engine hardcoded checks.
     */
    "builtin": boolean;

    /**
     * Fields is the list of fields rendered in the frontend config form (order = render
     * order). Each entry maps to one input (endpoint / api_key / secret / language etc.),
     * from which the frontend generates the form dynamically.
     */
    "fields": EngineFieldSchema[] | null;
}

/**
 * FieldWidget overrides the control shape. When empty, rendering follows Type by default
 * (string→text, secret→password); when set, a structured control is rendered instead, shared
 * by OCR and similar engines so "all config items are declared in engineSchemas".
 */
export enum FieldWidget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * WidgetOCRLangs is an OCR recognition-language multi-select (options from
     * OcrLangsOptions()); the value is joined with "+" into Extra.langs
     */
    WidgetOCRLangs = "ocr_langs",

    /**
     * WidgetOCRTimeout is the OCR timeout in seconds (positive integer), written to
     * Extra.timeout_sec
     */
    WidgetOCRTimeout = "ocr_timeout",

    /**
     * WidgetOCRCorrect is the OCR language-correction toggle, written to Extra.correct_text
     * (only meaningful for vision)
     */
    WidgetOCRCorrect = "ocr_correct",

    /**
     * WidgetOCRRetry is the Vision OCR failure-retry count (positive integer), written to
     * Extra.retry_count (only meaningful for vision)
     */
    WidgetOCRRetry = "ocr_retry",

    /**
     * WidgetOCRStatus is the tesseract install-status probe card (with an editable custom
     * binary-path endpoint), tesseract only
     */
    WidgetOCRStatus = "ocr_status",

    /**
     * WidgetLLMModel is the LLM translation engine's model name, a standalone text input whose
     * value is merged into Extra.model
     */
    WidgetLLMModel = "llm_model",
};

/**
 * TesseractStatus describes the local tesseract install probe result, for the frontend to
 * show install state per OS.
 */
export interface TesseractStatus {
    /**
     * Whether a tesseract executable was found
     */
    "installed": boolean;

    /**
     * The detected executable path (empty when not installed)
     */
    "path": string;

    /**
     * The detected version (empty when not installed), from `tesseract --version`
     */
    "version": string;

    /**
     * Current OS (darwin/linux/windows), lets the frontend pick the matching install command
     */
    "os": string;
}
