// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * LocaleChangedPayload carries the UI language change event.
 * Note: this is the UI display language — an entirely separate system from the translation
 * languages (model.Language: auto/zh/en/...); never mix them.
 * Mode is the user-configured UI language mode (auto / zh-CN / en-US);
 * Language is the actually active UI language (zh-CN / en-US; derived from the system locale
 * when auto).
 */
export interface LocaleChangedPayload {
    /**
     * UI language mode: auto | zh-CN | en-US
     */
    "mode": string;

    /**
     * Actually active UI language: zh-CN | en-US
     */
    "language": string;
}

/**
 * ScreenshotRetranslatePayload carries the screenshot-retranslate-after-language-change
 * event.
 * Session identifies the cache origin (ScreenshotSessionScreenshot /
 * ScreenshotSessionInput); the backend uses it to fetch that entry point's most recent OCR
 * text, keeping different entry points from bleeding into each other.
 * From/To are the target translation language pair (From may be Auto); the backend reuses
 * the most recent OCR text to retranslate.
 */
export interface ScreenshotRetranslatePayload {
    "session": string;
    "from": model$0.Language;
    "to": model$0.Language;
}

/**
 * ThemeChangedPayload carries the theme change event.
 * Mode is the user-configured mode (from model's ThemeAuto/ThemeLight/ThemeDark:
 * auto/light/dark);
 * Theme is the real system appearance (dark/light, derived from Env.IsDarkMode()).
 */
export interface ThemeChangedPayload {
    /**
     * settings: auto | light | dark
     */
    "mode": string;

    /**
     * settings: dark | light
     */
    "theme": string;
}
